version: "3.8"

services:
  z-service-ngrok:
    image: ngrok/ngrok:latest
    container_name: z-service-ngrok
    restart: unless-stopped
    command: http z-service-n8n:5678
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    ports:
      - "4040:4040"
    networks:
      - z-service-network

networks:
  z-service-network:
    external: true
